name: Release

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.releaseID }}
    steps:
      - name: Set up JDK 21
        # See https://github.com/actions/setup-java/releases/latest
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with:
          java-version: 21
          distribution: temurin
      - name: Checkout repository
        # See https://github.com/actions/checkout/releases/latest
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Setup Gradle
        # See https://github.com/gradle/actions/releases/latest
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
      - name: Build LimboTransfer
        run: ./gradlew build
      - name: Archive artifact
        # See https://github.com/actions/upload-artifact/releases/latest
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        if: success()
        with:
          name: LimboTransfer
          path: build/libs/LimboTransfer.jar
          if-no-files-found: error
      - name: Make release
        id: release
        # See https://github.com/Kas-tle/base-release-action/releases/latest
        uses: Kas-tle/base-release-action@b89ab10da9dfaa0b5fb0ca9e77679c7c7d1297f8
        with:
          files: |
            build/libs/LimboTransfer.jar
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}

  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: release
    steps:
      # See https://github.com/Kas-tle/release-build-log-action/releases/latest
    - uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.release.outputs.release_id }}